-- MySQL Script generated by MySQL Workbench
-- Sat Jun 15 21:38:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema new_db_cfsp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_db_cfsp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_db_cfsp` DEFAULT CHARACTER SET latin1 ;
USE `new_db_cfsp` ;

-- -----------------------------------------------------
-- Table `new_db_cfsp`.`maquina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_db_cfsp`.`maquina` (
  `idMaquina` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idMaquina`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `new_db_cfsp`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_db_cfsp`.`pedido` (
  `idPedido` INT(11) NOT NULL AUTO_INCREMENT,
  `semana` INT(11) NULL DEFAULT NULL,
  `fluxo` VARCHAR(1000) NULL DEFAULT NULL,
  `tempoTotal` INT(11) NULL DEFAULT NULL,
  `atendeuPedido` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`idPedido`))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `new_db_cfsp`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_db_cfsp`.`produto` (
  `idProduto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NULL DEFAULT NULL,
  `sequencia` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = MyISAM
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `new_db_cfsp`.`produto_has_maquina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_db_cfsp`.`produto_has_maquina` (
  `idProduto` INT(11) NOT NULL,
  `idMaquina` INT(11) NOT NULL,
  `custo` INT NULL,
  PRIMARY KEY (`idProduto`, `idMaquina`),
  INDEX `fk_produto_has_maquina_maquina1_idx` (`idMaquina` ASC) VISIBLE,
  INDEX `fk_produto_has_maquina_produto_idx` (`idProduto` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `new_db_cfsp`.`demanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_db_cfsp`.`demanda` (
  `idDemanda` INT(11) NOT NULL AUTO_INCREMENT,
  `cliente` VARCHAR(45) NULL,
  PRIMARY KEY (`idDemanda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_db_cfsp`.`demanda_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_db_cfsp`.`demanda_has_produto` (
  `idDemanda` INT(11) NOT NULL,
  `idProduto` INT(11) NOT NULL,
  `quantidade` INT(11) NULL,
  PRIMARY KEY (`idDemanda`, `idProduto`),
  INDEX `fk_demanda_has_produto_produto1_idx` (`idProduto` ASC) VISIBLE,
  INDEX `fk_demanda_has_produto_demanda1_idx` (`idDemanda` ASC) VISIBLE,
  CONSTRAINT `fk_demanda_has_produto_demanda1`
    FOREIGN KEY (`idDemanda`)
    REFERENCES `new_db_cfsp`.`demanda` (`idDemanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_demanda_has_produto_produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `new_db_cfsp`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_db_cfsp`.`pedido_has_demanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_db_cfsp`.`pedido_has_demanda` (
  `idPedido` INT(11) NOT NULL,
  `idDemanda` INT(11) NOT NULL,
  PRIMARY KEY (`idPedido`, `idDemanda`),
  INDEX `fk_pedido_has_demanda_demanda1_idx` (`idDemanda` ASC) VISIBLE,
  INDEX `fk_pedido_has_demanda_pedido1_idx` (`idPedido` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
